title: Graeme Ahokas
description: Software Developer and Project Manager
show_downloads: false
#theme: jekyll-theme-architect

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
